### ISSUE TITLE
Member variables not updating using var objects

### ISSUE THREAD

**Issue by MarkZ3** [lldb-tools/lldb-mi#25]
Using lldb-mi in master as of today (also seen with older versions)

Using this sample code:

class MyClass {
public:
	int field;
};

int main() {
	MyClass obj;
	obj.field = 5;
	obj.field = 4;
}

In Eclipse, if I step through the code, the value of 'obj.field' is not updated in the views. Looking at the MI traces, it looks like when the -var-create is done on 'obj', correctly but -var-update doesn’t report the change:

Using lldb-mi (macOS):
994,853 30-var-create --thread 1 --frame 0 - * obj
994,856 30^done,name="var0",numchild="1",value="{...}",type="MyClass",thread-id="1",has_more="0"
...
581,399 48-var-update 1 var0
581,403 48^done,changelist=[{name="var0",value="{...}",in_scope="true",type_changed="false",has_more\
="0"}]

Using GDB (Linux):
980,932 40-var-create --thread 1 --frame 0 - * obj
980,939 40^done,name="var1",numchild="1",value="{...}",type="MyClass",thread-id="1",has_more="0"
....
749,655 56-var-update 1 var1
749,655 56^done,changelist=[{name="var1.public.field",value="4",in_scope="true",type_changed="false"\
,has_more="0"}]

This is a major issue because it makes debugging non-trivial programs almost impossible.

Originating Eclips bug:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=503302
Old llvm bug:
https://bugs.llvm.org/show_bug.cgi?id=32100

**Comment by tkrasnukha** [comment]
Hi Marc-Andre,

If -var-update didn't report the change, it would send an empty changelist (`^done,changelist=[]`). In your example it reports that "var0"/"var1.public.field" has changed. And the value in the Linux case seems to be correct if Eclipse stepped over the line `obj.field = 4;`. Which value do you expect to see at that moment?

**Comment by tkrasnukha** [comment]
Sorry, I didn't note that the second example is using GDB. Anyway, lldb-mi's result implies that the requested variable has changed. 

The problem is that at https://github.com/lldb-tools/lldb-mi/blob/master/src/MICmnLLDBDebugSessionInfoVarObj.cpp#L276 GetValue is called with default argument `const bool vbExpandAggregates = false`.

**Comment by MarkZ3** [comment]
@anthony-kolesov Thanks a lot for fixing this! I think this was the main blocker to make lldb-mi really useable in Eclipse so this is a great step.
