### ISSUE TITLE
[Documentation] Building against system LLDB steps

### ISSUE THREAD

**Issue by pieandcakes** [lldb-tools/lldb-mi#36]
I'm trying to build lldb-mi to work against a shipped version of LLDB on macOS. Our goal is to still have `lldb-mi` be available but we can use `debugServer` that is available with XCode. 

Is that possible? If so, can I do it with XCode's installed LLDB toolset or what do I need to do differently? Also I noticed that instead of using `liblldb.dylib`, XCode has `LLDB.Framework` folder but I don't know how to change `lldb-mi` to support that scenario.

Any help would be appreciated.

**Comment by tkrasnukha** [comment]
PR #37 should make this possible. If building still doesn't work for you, feel free to re-open the issue.
