### ISSUE TITLE
Errors building with mingw-w64 toolchain

### ISSUE THREAD

**Issue by longnguyen2004** [lldb-tools/lldb-mi#43]
I was trying to compile with mingw-w64 and I noticed 2 errors regarding Platform.h and MIDataType.h
In Platform.h, I found a section wrapped inside an ```#ifdef _MSC_VER```, presumably for Windows detection. The problem is that it only works for MSVC. I suggest changing _MSC_VER to _WIN32, since that will work regardless of compiler used.
In MIDataType.h, the __int64 isn't defined by default in gcc. I suggest adding ```#include <windows.h>``` into the ```#ifdef _WIN32``` block, that way it'll get defined.

**Comment by RussellHaley** [comment]
Hi I am using a LLVM-Mingw64 toolchain. I've run into other problems building, but this would also affect me. I'm using the same compiler to cross build on FreeBSD, as well as a native Windows package.
https://www.github.com/mstorsjo/llvm-mingw

**Comment by tkrasnukha** [comment]
Hi folks, patches are appreciated, feel free to create a pull request.

**Comment by tkrasnukha** [comment]
Should be fixed by #52, re-open if needed.

**Comment by longnguyen2004** [comment]
Alright I'll check it out
