### ISSUE TITLE
Build cannot find LLVMConfig.cmake OR Error Behind Keyboard

### ISSUE THREAD

**Issue by RussellHaley** [lldb-tools/lldb-mi#49]
Hi, 

I'm using llvm-mingw to cross build itself on FreeBSD for Windows 10. My filesystem is laid out as so:
```
russellh@jailbird:/storage> tree -L 2
.
|-- build
|   |-- 2004
|   |-- llvm-mingw-host
|   `-- winlua-2004b.zip
|-- git
|   |-- libressl-portable
|   |-- lldb-mi
|   |-- llvm-mingw
|   |-- lua-5.3.4-op_halt
|   |-- luafilesystem
|   |-- luarocks
|   |-- sol2
|   `-- xmake
|-- physionet
|   |-- wfdb-10.6.2
|   `-- wfdb.tar.gz
|-- scripts
|   |-- README.md
|   |-- cmake
|   |-- license.txt
|   `-- winlua-build.sh
|-- sources
|   |-- netpgp-20140220
|   |-- orig_dir
|   |-- patches
|   |-- tars
|   |-- wlc-wrapper
|   |-- work
|   `-- zlib-1.2.11
`-- test.txt
```

llvm-mi is in `/storage/git/` and llvm is a under `/storage/git/llvm-mingw/llvm-project`. 

I would like to build lldb-mi for Windows. My LLVM Windows "installation" is in `storage/build/<arch>/WLC`. 

Build shell script:
``` bash
        cd /storage/git/lldb-mi
        mkdir build_$MINGW_PLATFORM
        cd build_$MINGW_PLATFORM

        echo $INSTALL_ROOT/$WIN_PLATFORM/WLC/
		
        cmake -GNinja -DBUILD_SHARED_LIBS=ON \
                -DCMAKE_TOOLCHAIN_FILE=$CMAKE_X_DIR/$MINGW_PLATFORM-w64-mingw32.cmake \
                -DCMAKE_PREFIX_PATH="$INSTALL_ROOT/$WIN_PLATFORM/WLC/" \
                -DCMAKE_INSTALL_PREFIX="$INSTALL_ROOT/$WIN_PLATFORM/WLC/lldb-mi" \
                ..
        ninja && ninja install
```

Output
```
mkdir: build_i686: File exists
/storage/build/2004/x86/WLC/
CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/storage/git/lldb-mi/build_i686/CMakeFiles/CMakeOutput.log".
ninja: error: loading 'build.ninja': No such file or directory
```

A search of my LLVM build directory finds: 

```
russellh@jailbird:/storage/git/llvm-mingw> find . -name "LLVMConfig.cmake"
./llvm-project/llvm/build-x86_64-w64-mingw32/cmake/modules/CMakeFiles/LLVMConfig.cmake
./llvm-project/llvm/build-x86_64-w64-mingw32/lib/cmake/llvm/LLVMConfig.cmake
./llvm-project/llvm/build/lib/cmake/llvm/LLVMConfig.cmake
./llvm-project/llvm/build/cmake/modules/CMakeFiles/LLVMConfig.cmake
./llvm-project/llvm/build-i686-w64-mingw32/cmake/modules/CMakeFiles/LLVMConfig.cmake
./llvm-project/llvm/build-i686-w64-mingw32/lib/cmake/llvm/LLVMConfig.cmake
```

So, finally my questions:
- Should I copy the LLVMConfig.cmake from my build directory to my installation directory? OR should I be pointing to my LLVM *build* directory?
- If I am to LLVMConfig.cmake, which file (modules, lib or arch specific?) should I move, and where should they be moved to?
- I wonder if the LLVM ninja install script should have copied LLVMConfig.cmake file? (That would denote there is possibly an error)

Any advice would be grand. 
Thanks!
Russell

**Comment by RussellHaley** [comment]
Ah, I didn't realize this project also ships with the main LLDB in LLVM. I'll build from the sources in there so cmake can find it's files.

**Comment by RussellHaley** [comment]
Hi, 
I'm sorry to be a pain. I'm still totally lost and still can't build lldb-mi. I thought the llvm-project had an lldb-mi folder, but I was incorrect (not sure where it came from, but it's empty except for an lldb-mi.exports file). 

Perhaps I'll try to simplify my question. My build is failing because it can't find LLVMConfig.cmake Your instructions say to point to the LLVM installation folder. Should my custom installation of LLVM include the LLVMConfig.cmake files that lldb-mi is looking for? I have only found those files in the *source* folders. That would at least tell me that my LLVM build is doing something incorrectly.

Thanks!
Russ

**Comment by tkrasnukha** [comment]
Hi @RussellHaley, sorry for the delayed response. LLVMConfig.cmake should be in the install directory. The only reason why they are not there I know is passing the option `-D LLVM_INSTALL_TOOLCHAIN_ONLY=On` when configuring LLVM. Is it your case?

Copying *.cmake files from the build directory is not going to work because paths in the build and install versions differ.

**Comment by RussellHaley** [comment]
Thanks for responding none the less!!! I don't remember that behaviour being documented in the LLVM build options so that's a great catch. I see the script I am using has an option for LLVM_INSTALL_TOOLCHAIN_ONLY. I'll head down that road.

**Comment by RussellHaley** [comment]
HA! It turns out the author of the scripts for building llvm-mingw actively stripped out the cmake files. 

Now I'm into real errors trying to cross compile for windows. I'll open a new issue if I need help. Thanks for your help!
