### ISSUE TITLE
Breakpoints under Windows, wrong file path returned by lldb-mi

### ISSUE THREAD

**Issue by vcouvert** [lldb-tools/lldb-mi#53]
Hello,

When reaching a breakpoint under Windows (I use Visual Studio Code with C/C++ extension), file path returned by lldb-mi is wrong.

For example, if my source file is D:/dir1/sudir1/file.cpp, file path returned by lldb-mi is D:dir1sudir1file.cpp.

Vincent

**Comment by tkrasnukha** [comment]
CLosed by #56
