### ISSUE TITLE
eclipse cdt fails, possibly because auf --interpreter

### ISSUE THREAD

**Issue by Fabian188** [lldb-tools/lldb-mi#67]
I have the version from Jan 15 2021. I was able to use this lldb-mi to debug with Eclipse with CDT on macOS 11.1.
After upgrading macOS to 11.2, debugging with Eclipse stopped working. I don't know if the upgrade was the reason.

Eclipse stalls starting the debug session. The started and running process (does not eat cpu) is 
`lldb-mi --interpreter mi2 --nx`

Calling this manually says
```
(gdb)
-file-exec-and-symbols "mi2"
^error,msg="Command 'file-exec-and-symbols'. Target binary 'mi2' is invalid. error: unable to find executable for 'mi2'"
(gdb)
```
While lldb-mi help says 
`--interpreter This option is kept for backward compatibility. This executable always run in MI mode`

Running manually `lldb-mi --nx` and then doing interactively `target create my_binary` works.

I assume that the 'interpreter' is not ignored as the help indicates but interpreted as executable. BTW, there is no help for `--nx`

**Comment by Fabian188** [comment]
No comment? It would really help me :)

**Comment by tkrasnukha** [comment]
Hi! Unfortunately, the issue may wait for a free developer for a long time. If it is urgent for you, feel free to create a pull request.

**Comment by Fabian188** [comment]
With pull request you mean I try to fix the issue myself? This is fair enough, given it is open source. Is there a way to ask specific questions to people who know the code?

**Comment by tkrasnukha** [comment]
There are no specific mailing lists/discussions for this project. I think you can ask questions right here.

**Comment by WardenGnaw** [comment]
@Fabian188 I believe the general usage for `--interpreter` is in the format of `--interpreter=<interpreter type>`. If its delimited by a space, it will take the next command as the executable.

Reference: [GDB Interpreter ](https://www.zeuthen.desy.de/dv/documentation/unixguide/infohtml/gdb/Interpreters.html)

You may be interested updating the MIDriver.cpp to handle the case where it does not provide `=` and take the next argument as the `<interpreter type>`.
https://github.com/lldb-tools/lldb-mi/blob/eafe11462f1e4a8561aed215c0462f06285d53a1/src/MIDriver.cpp#L358-L466

The other option is to have Eclipse update the command they send as `--interpreter=mi2`.

**Comment by MarkZ3** [comment]
Do you use the LLDB launcher in CDT? https://wiki.eclipse.org/CDT/User/FAQ#How_do_I_debug_with_LLDB.3F
When you do, it handles a few differences with GDB and if needed you could modify that code to handle the problem mentioned in this issue. I do think it would be better for lldb-mi to get closer to gdb though since it would also benefit other "mi" integrations.

**Comment by Fabian188** [comment]
Sorry for not responding. I tried current lldb-mi with current eclipse and current lldb from brew on current macOS 11.4 and it works. I don't know what solved the issue but at the moment I'm able to debug on macOS via lldb. Thanks to the ones to make this word
