### ISSUE TITLE
Windows breakpoint not working

### ISSUE THREAD

**Issue by acotty** [lldb-tools/lldb-mi#95]
I am working on trying to get the GDB/MI Code::Blocks plugin to use the lldb-mi.exe. I am currently using the llvm-mingw-20220323-msvcrt-x86_64 release. 

If i use the llgdb.exe V14.0.0 from MSYS2 (C:\msys64\clang64\bin\LLDB.exe) I can set a breakpoint and the response looks good.
If I use  lldb-mi.exe v14.0.0 from https://github.com/mstorsjo/llvm-mingw/releases/tag/20220323 I cannot set a breakpoint correctly. The response is not an error, but the data looks to be bad.

Both tests are using the same exe without it being rebuilt between tests a the tests were to change the debugger plugin.

This is the request and response summary for llgdb.exe:
request: breakpoint set --file main.cpp --line 127
response: Breakpoint 1: where = clang_Printf.exe`main + 719 at main.cpp:138:20, address = 0x00000001400018af

This is the request and response summary for lldb-mi.exe:
request: 10000000000-break-insert -f D:\Andrew_Development\Z_Testing_Apps\Clang_printf\main.cpp:71
response:10000000000^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",pending=["D:\Andrew_Development\Z_Testing_Apps\Clang_printf\main.cpp:71"],times="0",addr="0xffffffffffffffff",func="??",file="??",fullname="??/??",line="0",original-location="D:\Andrew_Development\Z_Testing_Apps\Clang_printf\main.cpp:71"}

Attached are the full debug logs for the two test. Please note that the plugin code for the llgdd.exe does not parse the breakpoint response as it has not been changed from the GDB/MI plugin.

Am I doing something wrong or is there a bug in the lldb-mi code?
[lldb-mi.txt](https://github.com/lldb-tools/lldb-mi/files/8478724/lldb-mi.txt)
[llgdb.txt](https://github.com/lldb-tools/lldb-mi/files/8478725/llgdb.txt)

**Comment by tkrasnukha** [comment]
At first glance escaping backslashes in the path argument of command `break-insert` can help

**Comment by royqh1979** [comment]
Confirmed.  I've tested the lldb-mi distributed with msys2 clang64 (mingw-w64-clang-x86_64-lldb-mi r83.2388bd7-1), and -break-insert always failed with 'not found', no matter '/' or '\' used as path delimiter:
`-break-insert  --source "G:\test.cpp" --line 6`
`^error,msg="Command 'break-insert'. Breakpoint location 'G:\\test.cpp' not found"`

`-break-insert  --source "G:/test.cpp" --line 6`
`^error,msg="Command 'break-insert'. Breakpoint location 'G:/test.cpp' not found"`

**Comment by royqh1979** [comment]
It seems that lldb doesn't recognize windows absolute file path starting with a drive letter and ':'
```
g:\>lldb test.exe
(lldb) target create "test.exe"
Current executable set to 'g:\test.exe' (x86_64).
(lldb) breakpoint set --file test.cpp --line 6
Breakpoint 1: where = test.exe`main + 38 at test.cpp:6:13, address = 0x0000000140001496
(lldb) breakpoint set --file g:\test.cpp --line 6
Breakpoint 2: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
(lldb) breakpoint set --file g:/test.cpp --line 6
Breakpoint 3: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
(lldb)
```

**Comment by acotty** [comment]
When moving to the DAP interface instead of MI it was found that on Windows you need to compile using -gdwarf-4 instead of -ggdb.
As such I am closing this issue as I no loner need it fixed.
